# Generated by Django 5.0.4 on 2024-04-20 23:56

import core.product.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('pricing', models.CharField(blank=True, choices=[('BSC', 'Basic'), ('STD', 'Standard'), ('PRM', 'Premium')], default='BSC', max_length=3, null=True)),
                ('free_trials', models.CharField(blank=True, choices=[('NONE', 'No Free Trial'), ('7D', '7 days'), ('30D', '30 days')], default='NONE', max_length=4, null=True)),
                ('image_url', models.ImageField(blank=True, max_length=2083, null=True, upload_to=core.product.models.product_directory_path)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True, max_length=2083, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('link', models.URLField(max_length=2083)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('statistics', models.JSONField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to=core.product.models.product_directory_path)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('edited', models.BooleanField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core_product.category')),
            ],
            options={
                'db_table': 'core.product',
            },
        ),
    ]
